import { mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outfile = path.join(root, 'public', 'project', 'convert.mjs');

await mkdir(path.dirname(outfile), { recursive: true });

await build({
  entryPoints: [path.join(root, 'src', 'pod', 'convert-entry.js')],
  outfile,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: ['node22'],
  minify: false,
  sourcemap: false,
  legalComments: 'none',
  banner: {
    js: "import { createRequire } from 'node:module'; const require = createRequire(import.meta.url);\n// Generated by npm run build:runner",
  },
});
